### ISSUE TITLE
¿Qué licencia usar?

### ISSUE THREAD

**Issue by pachadotdev** [visualizacion-uc/analisis-exploratorio-de-datos-y-principios-de-estadistica#1]
Veo que pusiste MIT. Esa la uso en todos mis proyectos de código.

En mis slides había usado CC 4.0

¿Migro a MIT?

**Comment by jbkunst** [comment]
Nah, tu que sabes más de licencias que yo me deberías recomendar que licencia usar. Me cambio a CC?

**Comment by pachadotdev** [comment]
el problema con CC es que el software se considera un "objeto físico", lo que te hace demandable en algunos estados y países si alguien usa tu material y desconfigura algo

**Comment by pachadotdev** [comment]
moví a MIT
