### ISSUE TITLE
RStudio server

### ISSUE THREAD

**Issue by pachadotdev** [visualizacion-uc/analisis-exploratorio-de-datos-y-principios-de-estadistica#2]
@jbkunst 

tengo un servidor con RStudio Server Pro ¿te sirve? ¿prefieres usar RStudio Desktop?

todo lo que hagas incide en lo que debo y no debo hacer luego

**Comment by jbkunst** [comment]
Si bien, creo que es muy bueno partir con RStudio Server dado que no tienen que instalar nada, practicamente llegar y usar; yo creo que usaré la versión de escritorio por que sería la forma más probable de uso (en caso que usen R en el futuro :sweat_smile:).

Preguntaré de todos modos a Ricardo si ya está instalado, y en caso que no esté y/o sea muy complejo de instalar abusaría de tu buena onda y solicitaría usar tu server :smile:.

**Comment by pachadotdev** [comment]
@jbkunst yo ya lo tengo configurado pensando justamente en maximizar la eficiencia del tiempo
